modLoader="lowcodefml"
loaderVersion="[40,)"
license="All Rights Reserved"
issueTrackerURL="https://github.com/FokaStudio/FSEE/issues"

[[mods]]
	modId="fsee"
	version="1.6a"
	displayName="FokaStudio's Ender Expansion"
	logoFile="pack.png"
	logoBlur=false
	authors="FokaStudio"
	description='''
		Harder End, new biomes, items and more!
	'''
	credits="Hex, misode, dfsek, Starmute"
	itemIcon="minecraft:ender_eye"
	displayURL="https://fokastudio.github.io/FSEE"

	[[dependencies.fsee]]
		modId="forge"
		mandatory=true
		versionRange="[40,)"
		ordering="NONE"
		side="BOTH"

	[[dependencies.fsee]]
		modId="minecraft"
		mandatory=true
		versionRange="[1.19,1.20)"
		ordering="NONE"
		side="BOTH"
